#!/bin/bash

# ========================================
# reCAPTCHA Enterprise iOS Setup Script
# Quick Reference & Final Steps
# ========================================

echo "📋 reCAPTCHA Enterprise iOS Setup - Final Steps"
echo "================================================"
echo ""

echo "✅ COMPLETED AUTOMATICALLY:"
echo "  1. RecaptchaEnterprise pod installed (v18.8.0)"
echo "  2. App Attest capability added to entitlements"
echo "  3. Code implementation complete"
echo "  4. Xcode build cleaned"
echo ""

echo "⏳ MANUAL STEPS REQUIRED:"
echo ""
echo "Step 1: Open Xcode and Add App Attest Capability"
echo "-------------------------------------------------"
echo "1. Open Xcode:"
echo "   $ open ios/Yoraa.xcworkspace"
echo ""
echo "2. In Xcode:"
echo "   - Select 'YoraaApp' target in the project navigator"
echo "   - Click 'Signing & Capabilities' tab"
echo "   - Click '+ Capability' button"
echo "   - Search for 'App Attest'"
echo "   - Add it to your app"
echo ""
echo "   ⚠️  This is REQUIRED for reCAPTCHA to work on iOS!"
echo ""

echo "Step 2: Configure Firebase Console"
echo "-----------------------------------"
echo "1. Go to: https://console.firebase.google.com"
echo "2. Select your project"
echo "3. Navigate to: Authentication → Settings → Sign-in method"
echo "4. Enable 'Phone' if not already enabled"
echo "5. Scroll to 'App verification for phone authentication'"
echo "6. Select 'reCAPTCHA Enterprise' (recommended)"
echo ""

echo "Step 3: Build and Test"
echo "----------------------"
echo "1. Clean and rebuild:"
echo "   $ cd ios && xcodebuild clean -workspace Yoraa.xcworkspace -scheme YoraaApp && cd .."
echo ""
echo "2. Run the app:"
echo "   $ npx react-native run-ios"
echo ""
echo "3. Test phone authentication:"
echo "   - Open phone login screen"
echo "   - Enter phone number with country code (e.g., +1234567890)"
echo "   - Click 'Send OTP'"
echo "   - Check for success (no 'reCAPTCHA SDK not linked' error)"
echo ""

echo "📁 FILES MODIFIED:"
echo "  - ios/Podfile (Added RecaptchaEnterprise)"
echo "  - ios/YoraaApp/*.entitlements (Added App Attest)"
echo "  - src/services/recaptchaService.js (NEW)"
echo "  - src/services/phoneAuthService.js (Updated)"
echo "  - App.js (Added initialization)"
echo ""

echo "🔍 VERIFICATION:"
echo "Check console logs for:"
echo "  ✅ '🔄 Initializing reCAPTCHA Enterprise for iOS...'"
echo "  ✅ '✅ Firebase Auth initialized with reCAPTCHA support'"
echo "  ✅ '📱 Verifying phone number with reCAPTCHA Enterprise'"
echo ""

echo "📚 DOCUMENTATION:"
echo "  - Full guide: RECAPTCHA_IOS_SETUP_COMPLETE.md"
echo "  - Official docs: https://cloud.google.com/recaptcha/docs/instrument-ios-apps"
echo ""

echo "🚀 QUICK START CHECKLIST:"
echo "  [ ] Open Xcode and add App Attest capability (CRITICAL)"
echo "  [ ] Enable reCAPTCHA Enterprise in Firebase Console"
echo "  [ ] Build and run the app"
echo "  [ ] Test phone authentication"
echo ""

echo "================================================"
echo "Ready to continue? Open Xcode with:"
echo "  $ open ios/Yoraa.xcworkspace"
echo "================================================"
