#!/bin/bash

echo "🔧 Configuring Firebase Phone Authentication for iOS"
echo ""
echo "The reCAPTCHA SDK error occurs because Firebase Phone Auth requires additional configuration."
echo ""
echo "⚠️  IMPORTANT: You need to complete these steps in Firebase Console:"
echo ""
echo "Option 1: Enable App Check (Recommended)"
echo "=========================================="
echo "1. Go to: https://console.firebase.google.com/project/yoraa-android-ios/appcheck"
echo "2. Click 'Get Started' or 'Add App'"
echo "3. Select your iOS app"
echo "4. Choose 'DeviceCheck' for production or 'Debug' for development"
echo "5. Click 'Save'"
echo ""
echo "Option 2: Configure reCAPTCHA Enterprise"
echo "=========================================="
echo "1. Go to: https://console.cloud.google.com/security/recaptcha"
echo "2. Select your project: yoraa-android-ios"
echo "3. Create a new site key for iOS"
echo "4. Add your bundle ID: com.yoraaapparelsprivatelimited.yoraa"
echo "5. Copy the site key"
echo "6. Go to Firebase Console > Authentication > Settings > Phone"
echo "7. Enable 'Phone sign-in' and add your reCAPTCHA site key"
echo ""
echo "Option 3: Disable App Verification (Development Only - NOT RECOMMENDED)"
echo "========================================================================="
echo "This is ONLY for development/testing and should NEVER be used in production!"
echo ""
echo "After completing any of the above options, rebuild your app:"
echo "  cd ios && pod install"
echo "  npx react-native run-ios"
echo ""
echo "📱 Current iOS Bundle ID: com.yoraaapparelsprivatelimited.yoraa"
echo "📦 Firebase Project ID: yoraa-android-ios"
echo ""
